apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: deploy-fbc-operator-run
  labels:
    upstream-usable: "true"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/nmars/tekton-integration-catalog.git
      - name: revision
        value: test-KONFLUX-12295
      - name: pathInRepo
        value: pipelines/deploy-fbc-operator/0.2/deploy-fbc-operator.yaml
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
